### ISSUE TITLE
[init]:global 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by RyuKwanKon** [Kusitms-28th-MeetUp-C/Server#1]
## Todo 🐳

- [x] issue template 작성
- [x] pr template 작성
- [x] .gitignore 설정
- [x] Readme 초안 작성
- [x] MainService 프로젝트 생성
- [x] WebsocketService 프로젝트 생성
