### ISSUE TITLE
[init]:global 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by RyuKwanKon** [Kusitms-28th-MeetUp-C/Server#1]
## 🍀 Description

프로젝트 기본 세팅

## 🍀 Todo
- [x] Issue Template 만들기
- [x] Pr Template 만들기
- [x] Service별 workflow 만들기
- [x] Service별 package 구조 만들기
- [x] git convention 공유
- [x] code convention 공유
