### ISSUE TITLE
[feat]:Global 서비스별 CI/CD 구현

### ISSUE THREAD

**Issue by RyuKwanKon** [Kusitms-28th-MeetUp-C/Server#3]
## 🍀 Description

Main, Socket Service별 CI/CD 구현

## 🍀 Todo
- [x] Main Service CI 구현
- [x] Main Service CD 구현
- [x] Socket Service CI 구현
- [x] Socket Service CD 구현
