### ISSUE TITLE
[chore] ci/cd 무중단 배포, 자동 배포, application.yml

### ISSUE THREAD

**Issue by qogustj** [Kusitms-28th-MeetUp-C/Server#9]
## Todo 🐳
- [ ] deploy.sh 작성
- [ ] Dockerfile 작성
- [ ] docker-compose 작성
- [ ] application.yml 작성
